version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "5000:5000" # Maps host port 5000 to container port 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=dotnet-commerce;Username=postgres;Password=nafiul1904hasan%#
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nafiul1904hasan
      POSTGRES_DB: dotnet-commerce
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
