name: .NET CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust this to your target framework version

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build the application
      - name: Build Application
        run: dotnet build --no-restore --configuration Release

      # Run Unit Tests
      - name: Run Tests
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      # Publish Test Results (Optional)
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults/*.trx'

  publish:
    name: Publish Application
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore and Build
      - name: Restore and Build
        run: |
          dotnet restore
          dotnet publish -c Release -o publish

      # Upload Published App (Optional)
      - name: Upload Published Application
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: publish/
